### ISSUE TITLE
javascript parse errors get eaten

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#10]
First off, thank you for putting this together. My game uses racer to run all of its game code, and the memory leaks made it impossible to ship / scale. It's got a chance now.

therubyracer has callstacks for where in the execution errors happened, but with mini_racer I don't get them:

```
var f = function(a, ) {};
"Unknown JavaScript Error during parse"
```

Is this because rubyracer does extra work on the other side of v8, or are these turned off on purpose by mini_racer-

any help is very much appreciated!

**Comment by SamSaffron** [comment]
I should be able to fix that

**Comment by seanmakesgames** [comment]
! was not expecting that! :D
Thank you :)

Also, I noticed Ruby exceptions that happen inside of marshalled Procs throw the same exception. <- that's much more managable, and preferred, as I don't want players seeing ruby exceptions they've caused through their code ;P

**Comment by SamSaffron** [comment]
Can you try latest out? can be improved a bit but we now provide locations

**Comment by seanmakesgames** [comment]
Pulling across and taking a look :D Thanks!

**Comment by SamSaffron** [comment]
I  want us to add support for

```
context.eval("a=1", name: 'bob.js')
```

cause that will allow us to untangle backtraces in a much cleaner way!

**Comment by seanmakesgames** [comment]
yeah-- would be cool. I've still yet to take advantage of the file feature for the game-- perf improvements not as important as stability atm! :D

Having the error message in there is good at least! Thanks for getting that in. :D
