### ISSUE TITLE
Cannot build macOS < 10.14 with Xcode 10?

### ISSUE THREAD

**Issue by ikasoumen** [discourse/mini_racer#107]
I tried installing mini_racer 0.2.2 with native extension on macOS 10.13.6 & Clang v10, but it failed.

An error messages as follow:
```
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Clang version: 
```
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

mini_racer [uses the macOS version to select the library](https://github.com/discourse/mini_racer/blob/master/ext/mini_racer_extension/extconf.rb#L27), but clang v10 does not have stdc++.
So macOS < 10.14 with Xcode 10 without gcc fails to build.

I tried `brew install gcc` and rebuild, build was completed.

**Comment by SamSaffron** [comment]
Interesting, let’s bump down the feature detection so we look at 10.13 and
up

**Comment by SamSaffron** [comment]
Can we feature detect based off running a clang command instead ?

**Comment by ignisf** [comment]
Hya,

From [Xcode 10 Release Notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes):

> Building with libstdc++ was deprecated with Xcode 8 and is not supported in
> Xcode 10 when targeting iOS. C++ projects must now migrate to libc++ and are
> recommended to set a deployment target of **macOS 10.9** or later, or iOS 7 or
> later. Besides changing the C++ Standard Library build setting, developers
> should audit hard-coded linker flags and target dependencies to remove
> references to libstdc++ (including -lstdc++, -lstdc++.6.0.9,
> libstdc++.6.0.9.tbd, and libstdc++.6.0.9.dylib). Project dependencies such as
> static archives that were built against libstdc++ will also need to be rebuilt
> against libc++. (40885260)

Now, if I understand this correctly they suggest we migrate to `libc++` and stop supporting darwin12 and lower. Having in mind that libv8 has binaries for darwin14+, I think we're safe to do so?

I very much dislike the idea of adding logic that determines the build environment. I've done it before with `libv8` and it was brittle and hacky.

**Comment by SamSaffron** [comment]
Sure let’s just do this unconditionally and see who complains
