### ISSUE TITLE
mac os error 

### ISSUE THREAD

**Issue by infinitytn** [discourse/mini_racer#112]
i get this error with my mac

> Seonghoonui-MacBook-Pro:peatio seonghoonju$ gem install mini_racer -v '0.2.0'
> Building native extensions. This could take a while...
> ERROR:  Error installing mini_racer:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /Users/seonghoonju/.rvm/gems/ruby-2.5.0/gems/mini_racer-0.2.0/ext/mini_racer_extension
> /Users/seonghoonju/.rvm/rubies/ruby-2.5.0/bin/ruby -r ./siteconf20181017-11290-1pq5qc0.rb extconf.rb
> checking for -lpthread... yes
> checking for -lobjc... yes
> creating Makefile
> 
> current directory: /Users/seonghoonju/.rvm/gems/ruby-2.5.0/gems/mini_racer-0.2.0/ext/mini_racer_extension
> make "DESTDIR=" clean
> 
> current directory: /Users/seonghoonju/.rvm/gems/ruby-2.5.0/gems/mini_racer-0.2.0/ext/mini_racer_extension
> make "DESTDIR="
> compiling mini_racer_extension.cc
> clang: warning: argument unused during compilation: '-rdynamic' [-Wunused-command-line-argument]
> In file included from mini_racer_extension.cc:2:
> In file included from /Users/seonghoonju/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby.h:33:
> In file included from /Users/seonghoonju/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:2036:
> /Users/seonghoonju/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/intern.h:47:19: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
> void rb_mem_clear(register VALUE*, register long);
>                   ^~~~~~~~~
> /Users/seonghoonju/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/intern.h:47:36: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
> void rb_mem_clear(register VALUE*, register long);
>                                    ^~~~~~~~~
> 2 warnings generated.
> linking shared-object mini_racer_extension.bundle
> clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]
> ld: library not found for -lstdc++
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [mini_racer_extension.bundle] Error 1
> 
> make failed, exit code 2
> 
> Gem files will remain installed in /Users/seonghoonju/.rvm/gems/ruby-2.5.0/gems/mini_racer-0.2.0 for inspection.
> Results logged to /Users/seonghoonju/.rvm/gems/ruby-2.5.0/extensions/x86_64-darwin-18/2.5.0/mini_racer-0.2.0/gem_make.out

from xcode 10 

> Building with libstdc++ was deprecated with Xcode 8 and is not supported in Xcode 10 when targeting iOS. C++ projects must now migrate to libc++ and are recommended to set a deployment target of macOS 10.9 or later, or iOS 7 or later. Besides changing the C++ Standard Library build setting, developers should audit hard-coded linker flags and target dependencies to remove references to libstdc++ (including -lstdc++, -lstdc++.6.0.9, libstdc++.6.0.9.tbd, and libstdc++.6.0.9.dylib). Project dependencies such as static archives that were built against libstdc++ will also need to be rebuilt against libc++. (40885260)

[https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes](url)

seems like you guys need to update

**Comment by ignisf** [comment]
Well... We did -- v0.2.3 addresses this.

**Comment by infinitytn** [comment]
Oh!!! thx didnt know... :) 👍
