### ISSUE TITLE
Remove instances of use of functions deprecated in V8 7.3

### ISSUE THREAD

**Issue by ignisf** [discourse/mini_racer#115]
- [x] Use of non-isolate version of `String::Utf8Value` https://github.com/v8/v8/commit/ce05578aa6606cf662984a968cc99d421cea30d8 (https://github.com/discourse/mini_racer/pull/116)
- [x] Use of non-maybe version of `Message::GetLineNumber` https://github.com/v8/v8/commit/5acf20551217ddce89c20c7c8848ae971eb192c2#diff-3dd7a0f46b1e5c1cc67921449e7180acL1781 (https://github.com/discourse/mini_racer/pull/117)
- [x] Use of non-maybe version of `TryCatch::StackTrace` https://github.com/v8/v8/commit/5acf20551217ddce89c20c7c8848ae971eb192c2#diff-3dd7a0f46b1e5c1cc67921449e7180acL9023 (https://github.com/discourse/mini_racer/pull/118)
- [x] Use of `V8::CreateSnapshotDataBlob` and `V8::WarmUpSnapshotDataBlob` instead of `SnapshotCreator` https://github.com/v8/v8/commit/b3738e658345adabaa958b9f9a94ca01fc87d5e4
- [x] Use of `String::Utf8Length` https://github.com/v8/v8/commit/3dd5c6fe38355b8323597341409b37f931de5a85
- [x] Use of `String::ToObject` https://github.com/v8/v8/commit/c8376b0069ebe16c67acf90c3cda3457ddccba4f
- [x] Use of `Local::ToString()` https://github.com/v8/v8/commit/c8376b0069ebe16c67acf90c3cda3457ddccba4f
- [x] Use of non-maybe version of `Value::Int32Value` https://github.com/v8/v8/commit/c8376b0069ebe16c67acf90c3cda3457ddccba4f
- [x] Use of non-maybe version of `Value::NumberValue` https://github.com/v8/v8/commit/c8376b0069ebe16c67acf90c3cda3457ddccba4f
- [x] Use of non-maybe version of `Date::New` https://github.com/v8/v8/commit/e84b92d7658dee79c34304a67c4fb84c93cd071b

**Comment by ignisf** [comment]
I am not sure how to handle the deprecation of Create/WarmUpSnapshotDataBlob. As far as I can see, they just deprecated these commodity functions in favour of leaving embedders to reimplement them by themselves? https://github.com/v8/v8/commit/b3738e658345adabaa958b9f9a94ca01fc87d5e4

**Comment by ignisf** [comment]
@SamSaffron, I've updated the list of incompatibilities here.

**Comment by ignisf** [comment]
I've made some progress here (am yet to write descriptive commit messages) https://github.com/discourse/mini_racer/compare/v8-7.3-wip

**Comment by SamSaffron** [comment]
awesome work! I say if we are stuck cut and pasting code cause that is what they expect we got to do it with the snapshots.

**Comment by ignisf** [comment]
A sneak peek:

```
# Running:

...........................S...........<unknown>:65: Uncaught TypeError: Cannot create property 'kevin' on number '2'
...........................S.....

Fabulous run in 1.649479s, 43.6502 runs/s, 78.2065 assertions/s.

72 runs, 129 assertions, 0 failures, 0 errors, 2 skips
```

**Comment by ignisf** [comment]
@SamSaffron, care to take a look at the non-trivial changes I made in the branch? It's the last two commits.

**Comment by ignisf** [comment]
Also, do you have any suggestions how to properly attribute the copied-over functions from V8's test suite?

**Comment by SamSaffron** [comment]
I think a comment at the beginning of where you cut pasted should be fine, the license is compatible. 

Overall I am :+1:  here, feel free to merge it in
