### ISSUE TITLE
Migrating from therubyracer

### ISSUE THREAD

**Issue by afdev82** [discourse/mini_racer#119]
Hi,
I'm trying to migrate from therubyracer and I have the following problem:

```
context['I18n'] = I18n
context['console'] = Console.new
```
I use this code with `therubyracer` and it's working fine, to call the methods in ruby.
I saw there is an `attach` method in `mini_racer` and I'm trying to use it to get the same result, but I'm not sure how to do it.
Is it possible to do the same or should I redefine each method one by one with a `proc`?

**Comment by afdev82** [comment]
For the moment I have done in this way:

```
ctx.attach('I18n.t', lambda { |key, options = nil|
      key = Array(key).join '.'
      options.transform_keys!(&:to_sym) if options.present?

      I18n.t(key, options)
    })
```
but I wonder if there is a better way.

**Comment by SamSaffron** [comment]
We opted for a very simple and explicit interface to avoid a lot of the pain therubyracer experienced over the years, this is how we are still up to date with v8. 

The boundaries are far cleaner in mini racer, your attach example is the way to go.
