### ISSUE TITLE
[Question] Safe to run untrusted code?

### ISSUE THREAD

**Issue by awinograd** [discourse/mini_racer#132]
Thanks for a great gem! Sorry if this isn't the right place for questions.

Is it safe to run untrusted (i.e. user-provided code) in a `MiniRacer::Context`? I understand I'd have to prevent resource exhaustion via timeout/memory management, but I can't 100% figure out if v8 provides me a totally sandboxed environment otherwise so I don't need to worry about untrusted code making network requests or using the filesystem.

I myself have tried to run "dangerous" code and haven't been able to but wanted to double check.

Thanks again!

**Comment by SamSaffron** [comment]
I know @seanmakesgames does stuff like this and we fixed many issues over the years. 

You don't need to worry about network or disk, but ought to put a timeout and memory limit on the context so user does not spin it forever or eat too much memory.

**Comment by awinograd** [comment]
Sounds great. Thank you @SamSaffron!

**Comment by ignisf** [comment]
That said, you should always err on the side of caution as indeed you're running untrusted code. You should employ several layers of protection, including separating the processes that execute untrusted JS on different systems which have no access to critical infrastructure.

**Comment by awinograd** [comment]
Thanks for the extra resources & input @ignisf. That's a lot of good stuff to think about.
