### ISSUE TITLE
Problems with install mini_racer 0.2.4 (Ubuntu 19.04)

### ISSUE THREAD

**Issue by MikkelDK** [discourse/mini_racer#146]
Hello,

I'm using Ubuntu 19.04
Ruby version: 2.5.5p157.

I have weird problems with install "mini-racer 0.2.4.
What can I do?

Error:
```
current directory: /var/lib/gems/2.5.0/gems/mini_racer-0.2.4/ext/mini_racer_extension
/usr/bin/ruby2.5 -I /usr/local/lib/site_ruby/2.5.0 -r ./siteconf20190708-20427-hqzjbk.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.5
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- libv8 (LoadError)
        from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from extconf.rb:2:in `<main>'

extconf failed, exit code 1
```

Update 2:
If I edit on `gemfile` -> and adding: `gem "mini_racer", "~> 0.2.4"` - and try again, it installs 0.2.6 and NOT 0.2.4! ;-/

**Comment by ignisf** [comment]
1. What is stopping you from using the latest version of `mini_racer`?
2. If you in fact REQUIRE the use of the 0.2.4 version of `mini_racer`, you'll need to cap the version of `libv8` because of this: https://github.com/discourse/mini_racer/blob/master/CHANGELOG#L14

**Comment by MikkelDK** [comment]
Hi @ignisf 

it's because I'm using this software: https://github.com/Arie/serveme

Which have only 0.2.4 version!

**Comment by ignisf** [comment]
@Arie, could you please bump the version of `mini_racer` you're using, because the current one has a known compatibility issue?
