### ISSUE TITLE
How to use mini_racer with rails safely?

### ISSUE THREAD

**Issue by bbozo** [discourse/mini_racer#149]
Hi :-)

In the context of forking-safety - https://github.com/discourse/mini_racer#fork-safety - I'm wondering if there's anything to do with typical rails forking setups that needs to be taken care of when using mini_racer with execjs?

My concern at the moment is puma, but similar principles would apply to others

It'd be a great addition to the docs too (something like "If you're using a Rails forking server, you're fine" - or not :-))

**Comment by SamSaffron** [comment]
Not sure if there is more to write beyond what I added to the docs. 

v8 is not fork safe and there are no built in Ruby hooks for figuring out if a fork happened or not. 

The key is to throw away every single v8 context you have prior to forking.

**Comment by bbozo** [comment]
True, I'm sorry, was burnt out yesterday, on puma we should just clear contexts in Puma's before_fork ^_^
