### ISSUE TITLE
Can't marshal DateTimes

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#15]
I looked into this a bit, and it seems there are some performance considerations,
I was not able to find a rb_cDateTime const in the c api for ruby, so we have to make one for ourselves by doing "DateTime.new.class" or something and saving that
I don't know the code well enough to know where to put that so that it wouldn't get called **every** serialization

**Comment by SamSaffron** [comment]
Simplest would be to do it on init (bottom of file) and store in a static

**Comment by seanmakesgames** [comment]
Sounds good. Got that going, but now there are inconsistencies between the rails console and the test case: says NoMethodError: undefined method `to_f' for #<DateTime:0x007fda52965620>

Which it has in my experiments.

**Comment by seanmakesgames** [comment]
ha! 'fixes' worked. :)
