### ISSUE TITLE
Can't install mini_race gem on Windows

### ISSUE THREAD

**Issue by blacksky86** [discourse/mini_racer#17]
I'm following [this thread](http://blog.discourse.org/2013/04/discourse-as-your-first-rails-app/), that shows you how to install Disocurse using Vagrant. Everything goes well until I do "Bundle Install", most gems install fine but there seems to be a problem with this one. I get the following error message:

"An error occurred while installing mini_racer (0.1.3), and Bundler cannot continue.
Make sure that `gem install mini_racer -v '0.1.3'` succeeds before bundling." 

Which doesn't say much, so I tried to install it as it says and I get this:

Building native extensions.  This could take a while...
ERROR:  Error installing mini_racer:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20160528-1821-euyqum.rb extconf.rb
checking for main() in -lpthread... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling mini_racer_extension.cc
In file included from mini_racer_extension.cc:4:0:
/var/lib/gems/2.2.0/gems/libv8-5.0.71.48.3-x86-linux/vendor/v8/include/v8.h:341:1: error: expected unqualified-id before ‘using’
/var/lib/gems/2.2.0/gems/libv8-5.0.71.48.3-x86-linux/vendor/v8/include/v8.h:477:1: error: expected unqualified-id before ‘using’
/var/lib/gems/2.2.0/gems/libv8-5.0.71.48.3-x86-linux/vendor/v8/include/v8.h:871:1: error: expected unqualified-id before ‘using’
mini_racer_extension.cc:136:51: error: ‘Handle’ has not been declared
mini_racer_extension.cc:136:57: error: expected ‘,’ or ‘...’ before ‘<’ token
mini_racer_extension.cc: In function ‘VALUE convert_v8_to_ruby(v8::Isolate*, int)’:
mini_racer_extension.cc:140:9: error: ‘value’ was not declared in this scope
mini_racer_extension.cc:144:9: error: ‘value’ was not declared in this scope
mini_racer_extension.cc:148:9: error: ‘value’ was not declared in this scope
mini_racer_extension.cc:152:9: error: ‘value’ was not declared in this scope
mini_racer_extension.cc:156:9: error: ‘value’ was not declared in this scope
mini_racer_extension.cc:160:9: error: ‘value’ was not declared in this scope
mini_racer_extension.cc:165:55: error: cannot convert ‘v8::Local<v8::Value>’ to ‘int’ for argument ‘2’ to ‘VALUE convert_v8_to_ruby(v8::Isolate*, int)’
mini_racer_extension.cc:171:9: error: ‘value’ was not declared in this scope
mini_racer_extension.cc:175:9: error: ‘value’ was not declared in this scope
mini_racer_extension.cc:184:53: error: cannot convert ‘v8::Local<v8::Value>’ to ‘int’ for argument ‘2’ to ‘VALUE convert_v8_to_ruby(v8::Isolate*, int)’
mini_racer_extension.cc:186:57: error: cannot convert ‘v8::Local<v8::Value>’ to ‘int’ for argument ‘2’ to ‘VALUE convert_v8_to_ruby(v8::Isolate*, int)’
mini_racer_extension.cc:193:26: error: ‘value’ was not declared in this scope
mini_racer_extension.cc: At global scope:
mini_racer_extension.cc:197:8: error: ‘Handle’ does not name a type
mini_racer_extension.cc: In function ‘VALUE rb_context_eval_unsafe(VALUE, VALUE)’:
mini_racer_extension.cc:299:61: error: cannot convert ‘v8::Local<v8::Value>’ to ‘int’ for argument ‘2’ to ‘VALUE convert_v8_to_ruby(v8::Isolate*, int)’
mini_racer_extension.cc:306:63: error: cannot convert ‘v8::Local<v8::Value>’ to ‘int’ for argument ‘2’ to ‘VALUE convert_v8_to_ruby(v8::Isolate*, int)’
mini_racer_extension.cc:348:56: error: cannot convert ‘v8::Local<v8::Value>’ to ‘int’ for argument ‘2’ to ‘VALUE convert_v8_to_ruby(v8::Isolate*, int)’
mini_racer_extension.cc: In function ‘void* gvl_ruby_callback(void*)’:
mini_racer_extension.cc:396:2: error: ‘Handle’ was not declared in this scope
mini_racer_extension.cc:396:17: error: expected primary-expression before ‘>’ token
mini_racer_extension.cc:396:19: error: ‘external’ was not declared in this scope
mini_racer_extension.cc:396:45: error: expected primary-expression before ‘>’ token
mini_racer_extension.cc:396:46: error: ‘::Cast’ has not been declared
mini_racer_extension.cc:409:65: error: cannot convert ‘v8::Local<v8::Value>’ to ‘int’ for argument ‘2’ to ‘VALUE convert_v8_to_ruby(v8::Isolate*, int)’
mini_racer_extension.cc:430:2: error: ‘Handle’ was not declared in this scope
mini_racer_extension.cc:430:14: error: expected primary-expression before ‘>’ token
mini_racer_extension.cc:430:16: error: ‘v8_result’ was not declared in this scope
mini_racer_extension.cc:430:73: error: ‘convert_ruby_to_v8’ was not declared in this scope
make: *** [mini_racer_extension.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.2.0/gems/mini_racer-0.1.3 for inspection.
Results logged to /var/lib/gems/2.2.0/extensions/x86-linux/2.2.0/mini_racer-0.1.3/gem_make.out

Windows 10, 64 bit 
Ruby 2.2.2p95

**Comment by ignisf** [comment]
Hello,

I think that currently the Ruby DevKit includes gcc 4.7 and using gcc v4.8 or newer is required for installing mini_racer.

To add to that, the libv8 gem currently does not have windows support and I am somewhat curious how did your installation fail at mini_racer instead of libv8.

**Comment by ignisf** [comment]
Oh, disregard what I said above, I thought you were installing on the windows host itself. You just need to install gcc 4.8 or newer in your Vagrant box. Check http://ubuntuhandbook.org/index.php/2013/08/install-gcc-4-8-via-ppa-in-ubuntu-12-04-13-04/ how to do this in Ubuntu. Not sure what's in the box distributed by Discourse.

**Comment by SamSaffron** [comment]
Yes, you are going to need GCC 4.8 or above. 

GCC 4.8.1 was released May 31, 2013, 3 years ago, tomorrow.

**Comment by ignisf** [comment]
@SamSaffron, just as a note, if you plan to roll out a discourse version that depends on mini_racer, you should probably account for this in the Vagrant box.

**Comment by blacksky86** [comment]
Awesome, @ignisf , that works, up and running with 4.8 :smile: , Thanks

**Comment by blacksky86** [comment]
Just that I can't seem to login to the backend for some reason, and new activations are not happening cause the email won't get send

**Comment by SamSaffron** [comment]
@blacksky86  this is not related to mini_racer, maybe to a post about it on meta.discourse.org under dev category.
