### ISSUE TITLE
global exception management

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#25]
My players have written JS that looks like the following:

```
function(context, args)
{
	var o={};
	o.__defineGetter__('bar',function(){

		for(var i=0;i<10;++i)
			some_rb_attached_method({data:"foo"});
		return 2
	});
	return o
}
```

which gets evaluated after the .eval() block on the context. e.g:

```
result = ctx.eval(above_code)
ctx.stop
ActiveSupport::JSON.encode(result) # or something similar
```

This will throw a c-extension exception in mini_racer
`/mini_racer.rb:96: [BUG] rb_thread_call_with_gvl: called by a thread which has GVL.`

I can fix this error (several solutions), but what I really want is to be able to catch these and log them somehow on the server, so that I can fix them. Right now I think they disappear into the void.

Ideally, I'd like this code to be safe, (catch in c, safe & consistent log, and rethrow; to terminate if it's a fatal issue)

Any thoughts?

**Comment by SamSaffron** [comment]
We can not have any bugs like this, can you make an exact test case that repros the error so I can have a look?

**Comment by seanmakesgames** [comment]
Yep. Also one of my players found a simplified version of this that throws something else.

```
v8 = MiniRacer::Context.new
v8.eval 'var o = {}; o.__defineGetter__("bar", function() { return null(); }); o'
```

throws  [BUG] Segmentation fault at 0x00000000000027

**Comment by SamSaffron** [comment]
excellent, confirmed here, having a look ...

**Comment by ethankaminski** [comment]
As one of the co-miscreants here (specifically, the one who found the standalone segfault version), here are some other JS snippets that cause a segfault at 0x27 when used as the body of the getter function:

`throw 1;`
`return no_such_var;`
`return no_such_var();`
`return 1();`

Wrapping the `null()` version in a try/catch successfully prevents the segfault. Maybe it's an issue handling JS exceptions in a particular section of code?

Here's a snippet which is not repairable by a try/catch, and which also gives the error message `Exception thrown during bootstrapping` before the segfault:

`return o; // this probably does something screwy with recursion?`

**Comment by SamSaffron** [comment]
I fixed the segfault, recovering a clean backtrace requires some extra jiggling, feel free to send a PR for it provided we are not adding code duplication there

**Comment by seanmakesgames** [comment]
The provided example was just one of many potential exceptions-- do you know of a way that these c-exceptions can be logged / are already logged?

Right now, my server code just dies w/ no reporting of any kind.

**Comment by seanmakesgames** [comment]
Sorry- looked at the code and ran the test. I assume this will handle conversion exceptions nicely.
Do you have any suggestions for getting information on other exceptions that happen on production?

**Comment by SamSaffron** [comment]
its fiddly but straight forward, we need to translate whatever information
the trycatch returns (there is an example in the file below) then pass that
information into the conversion error object and when raising pass it in to
the runtime error. That way we keep info about the exeption type and so on.

**Comment by ethankaminski** [comment]
I also found a self-contained way to reproduce the `rb_thread_call_with_gvl: called by a thread which has GVL.` error message, using the pre-patch gem version. I'm not sure how to successfully build the C extension myself, so I'll let @seanmakesgames or Sam test whether this variation is fixed.

```
require 'mini_racer'
v8 = MiniRacer::Context.new
v8.attach 'print', proc{|o| puts o}
puts v8.eval "o = {get bar() { print(42); }}; o"
```

**Comment by seanmakesgames** [comment]
I'm using something like
`rake clean compile test TEST=test/mini_racer_test.rb TESTOPTS="--name=test_case_name -v"`
for running the tests.
Does that look right @SamSaffron ?

**Comment by SamSaffron** [comment]
something like that, I usually run all the tests

**Comment by SamSaffron** [comment]
@ethankaminski, yeah that is a diff error, seeing how to sort it out ...

**Comment by SamSaffron** [comment]
reopening due to the second error which is far harder to sort out.... 

its actually quite a nightmare, simplest thing is not to allow getters to external functions ...

**Comment by seanmakesgames** [comment]
I'm 100% on board with that.

**Comment by seanmakesgames** [comment]
To be clear, though-- I opened this issue not to solve these two exceptions (which I am very much appreciative of) but instead to:

 > get something in place to have a global catch-all of some sort, with some logging

so that we can continue to file & fix these things as we find them

**Comment by SamSaffron** [comment]
"get something in place to have a global catch-all of some sort, with some logging" this is impossible, we need to deal with the specific issues here. In particular the conversion code is unsafe assumes it will never exception out or execute ruby code, both those assumptions are incorrect so it needs fixing. 

there is no way to set a global catch all programming errors thing in place :)

**Comment by ethankaminski** [comment]
The second error seems to only occur when calling an external function from a getter inside the final JS-to-Ruby conversion. If I change the JS to `o = {get bar() { print(42); }}; o.bar; 1`, it successfully prints "42" and "1". Similarly, changing the final statement to `JSON.parse(JSON.stringify(o))` renders it safe for the conversion code.

Hmm... thinking about general applications (i.e., including things other than Sean's game)... external functions inside getters _within_ JS could be useful, but they don't need to be available at the JS-Ruby boundary. Is there some way to block external functions specifically in that final JS-to-Ruby statement?

**Comment by SamSaffron** [comment]
Yeah it can be fixed, we just need to re-engineer some of this boundary code

**Comment by ethankaminski** [comment]
@seanmakesgames: one thing I can think of is reading stderr of the process in question, and checking for the substring `[BUG]`, or any other weird output. That would at least let you trigger an alert. I think segfaults aren't really a recoverable state, so there might not be a same-process way to check for such errors.

@SamSaffron: :salute:.

**Comment by SamSaffron** [comment]
this is going to take a while to fix, @wk8 @seanmakesgames if you want to try it out be my guest. 

In essence in convert_v8_to_ruby we must release the GVL prior to calling `object->Get` to grab the value. 

that is done using `rb_thread_call_without_gvl` but the tricky thing is passing the V8 object back and cleaning up properly without leaking.

**Comment by seanmakesgames** [comment]
Oof. So there's no way to do the conditional (throw exception on 'call attached func' during v8convert)?

**Comment by SamSaffron** [comment]
not really, the attached function needs to be aware of this state somehow, injecting and cleaning up that state would be even harder than calling it without a gvl

**Comment by seanmakesgames** [comment]
got it. that sucks. Alrighty then, I'll take a stab at it when I can. Got any pointers on the mem cap thing I'm trying to do? (other issue)

**Comment by seanmakesgames** [comment]
@SamSaffron Can you give me some pointers on:
```
		 // TODO isolate code that translates execption to ruby
		 // exception so we can properly return it
```
Timeouts are happening during marshalling, and are just sending FailedV8Conversion objects into rubyland (where I'm currently just assuming that they are timeouts)

I've got a test with consistent repro, if you're curious:
```
  def test_timeout_during_marshall
    context = MiniRacer::Context.new({timeout: 1000})
    context.attach("long_running_proc", proc do |a|
      a[rand(10000).to_s] = "a"
      a
    end)
    assert_raises(MiniRacer::ScriptTerminatedError) do
      context.eval("var a = {}; while(true) { a = long_running_proc(a); }")
    end
  end
```

**Comment by SamSaffron** [comment]
@seanmakesgames can you open a new ticket on that timeout issue, I fixed the OP here these segfaults should be gone (can you test)

**Comment by seanmakesgames** [comment]
verified. Thanks for the fix! (created other issue)
