### ISSUE TITLE
mini_racer won't install on Travis

### ISSUE THREAD

**Issue by schneems** [discourse/mini_racer#26]
Any ideas? Here's the build output: https://travis-ci.org/codetriage/codetriage/jobs/142931841

**Comment by ignisf** [comment]
See #9

**Comment by schneems** [comment]
Thanks, can we detect GCC version and raise an error or output a warning?

**Comment by ignisf** [comment]
I personally would advise against burdening this gem with compiler brand/version detection logic, as seen in `libv8` for example. It's flaky at best and I would have gotten rid of it if it wasn't necessary for passing different flags to V8's build system depending on compiler brand.

A better approach would be to check for C++11 support and fail with a message that explicitly states what's wrong.

An easy way to do this could be to replace [this option](https://github.com/discourse/mini_racer/blob/master/ext/mini_racer_extension/extconf.rb#L10) with `-std=c++11`. I think it should fail with `unrecognized command line option '-std=c++11'` on compilers lacking the necessary functionality, which is *somewhat* clearer.

The correct way of checking what version of the C++ standard is supported I think is by looking at the value of the `__cplusplus` macro. I don't know if and how one can do anything with `mkmf` with macros, apart from check if they're defined.

Alternatively, if no elegant way of doing so with `mkmf` is available, the `extconf.rb` file could run `ENV['CXX'] -E` with the correct `CPPFLAGS` on the following, and abort the compilation if the compiler returns an error:

```c++
#if __cplusplus <= 199711L
#   error A compiler that supports at least C++11 is required in order to compile this project.
#endif
```

@SamSaffron, what do you think?

**Comment by SamSaffron** [comment]
@ignisf sure go for it, this keeps popping up.

**Comment by SamSaffron** [comment]
I think @ignisf just fixed this in libv8

**Comment by ignisf** [comment]
Nope
