### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by darix** [discourse/mini_racer#27]
there are a lot of fixes since 0.1.4 including the patch that would allow using a v8 newer than 5.1.11. 

anything blocking a release atm?

**Comment by wk8** [comment]
That'd be great indeed :)

**Comment by SamSaffron** [comment]
I want to do a release, but I am uneasy to do so with the open segfault. I want that fixed first.

**Comment by SamSaffron** [comment]
@darix  @wk8 if you can test latest it would help, let me know if it looks good to you and I will bump

**Comment by seanmakesgames** [comment]
ran full test suite against latest and I'm getting strange hangs (have to kill -9) in random test cases. It's probably my fault, but I should probably check it out it the morning because it's late here

here're the callstacks from my gdb attach. lmk if you see anything weird.
https://gist.github.com/seanmakesgames/e93830060acfb0e07ce232d072d81fc4

**Comment by seanmakesgames** [comment]
I lied, I tried one thing, now I'm going to bed. Rolling back to one behind latest commit solved the hangs. 
(sync'd to 31ec118)

**Comment by SamSaffron** [comment]
ouch, if you have a proper repro let me know I will have a look, not going
to release anything unstable.

**Comment by seanmakesgames** [comment]
filed #30 for tracking

**Comment by wk8** [comment]
@SamSaffron : I'm on vacation for another couple of weeks, but happy to help after that, if it can do any good? thanks!

**Comment by SamSaffron** [comment]
@wk8 I will try to get out a release earlier, have a great time on your holiday, feel free to check back in when you are back :)

**Comment by seanmakesgames** [comment]
Ran the full test suite against latest with latest libv8. All checks out. :)

**Comment by darix** [comment]
So time for a release now?

**Comment by SamSaffron** [comment]
@darix I really want to release, but @seanmakesgames has been saying the latest still segfaults in some conditions and I want to sort that out before doing a release, I need a consistent repro of segfaults

**Comment by seanmakesgames** [comment]
@SamSaffron This segfault undoubtedly was in previous releases. It is a relatively 'low repro rate' for most user cases. I just happen to be hitting them frequently because I create hundreds of thousands of contexts a day.
I'm going to set up valgrind and see if we can get more clarity on uninitialized memory instances, hopefully that will get us a more consistent repro.

**Comment by seanmakesgames** [comment]
@darix Not sure how you're referencing the library, but if you're using a gemfile, then you could just ref the github@specific version until we get a release out.

`gem 'mini_racer', github: 'discourse/mini_racer', ref: 'dbb4cef'`

**Comment by darix** [comment]
while this would definitely work .... I prefer to package my gems as rpms for various reasons. among other things i package discourse and my discourse package is stuck because i cant upgrade mini_racer, because i want to use the system copy of v8.

**Comment by seanmakesgames** [comment]
makes 100% sense. :)

**Comment by ignisf** [comment]
> i want to use the system copy of v8

Glad to hear that's working at least for somebody

**Comment by SamSaffron** [comment]
@seanmakesgames just to confirm, you are not able to make segfaults happen in latest?

**Comment by seanmakesgames** [comment]
Not confirmed. 
Just had 2 segfaults on production in the last 30 minutes.
I'm not able to make segfaults happen in test cases, but I haven't set up valgrind yet.

**Comment by SamSaffron** [comment]
@wk8 if you feel like helping test this for segfaults it would be awesome, I don't want to release till we are very solid.

**Comment by SamSaffron** [comment]
@ignisf I feel stuff is a bit more stable following my work yesterday ... perhaps you can do a build with v8 5.3 and then we can push a new mini_racer with that. 

Once you have it ready I will push a pre-release and then 1 week later push stable.

**Comment by ignisf** [comment]
Will look into it.

**Comment by ignisf** [comment]
@SamSaffron @seanmakesgames beta libv8 up on rubygems

**Comment by SamSaffron** [comment]
@ignisf awesome, I will set a hard dependency on it in the upcoming release 

@seanmakesgames any new on the segfaulting?

**Comment by ignisf** [comment]
Just run some tests to check if everything is OK and ping me and I'll make a non-prerelease

**Comment by seanmakesgames** [comment]
@SamSaffron oof. I totally updated my fork and my lockfile, but that never got pushed up to production. :(
It's been a busy week though with pax, so makes sense that I missed something. :\
However! I'm currently creating a framework for load testing (to find max concurrency numbers), and that will surely be able to quickly tell if the other segfaults are fixed or not. I'll keep you posted.

**Comment by seanmakesgames** [comment]
@SamSaffron got a c-level exception. Potentially uninit memory or the utf-8 / utf-16 border.

https://gist.github.com/seanmakesgames/fa4e610029cbced26da7e3a587717c30

haven't set up the load tests yet either. Will keep you posted.

**Comment by SamSaffron** [comment]
Dealing with junk strings in Ruby is annoying, that is actually a legit
error, perhaps you should be running #scrub on strings you are sending in?

**Comment by seanmakesgames** [comment]
Can do. Not sure why it's failing in c-extension-land, and not raising inside of ruby where I would have caught it and returned it to players. :\

**Comment by seanmakesgames** [comment]
made another issue for the most common segfault (I'm sure it shows up in other gitissues, too, but figured I'd pull it out into its own)
https://github.com/discourse/mini_racer/issues/39

Can someone tell me why the junk strings are causing c-land exceptions instead of raising in ruby?

**Comment by darix** [comment]
well what you actually want is having the JS exception handled and converted into a ruby exception?

**Comment by seanmakesgames** [comment]
Oh @darix! The "String String ��� is not valid UTF-8." is a JS exception? 
Also welcome back. Hope your vacation was good :)

**Comment by darix** [comment]
well it would be interesting to see with some debug prints if it is still ruby or already in JS. in general i would see

1. make sure your web app sets all encodings to UTF-8 so that you can hopefully treat all strings as UTF-8
2. scrub anything that isnt valid UTF-8. having a common safe encoding when mixing languages is a good idea. e.g. i really wonder why it says ASCII-8BIT there.

**Comment by seanmakesgames** [comment]
haha @darix. :\ :P
This exception is coming from inside JS code which is natively utf-16. That code is being run on the server, which is calling into a ruby function.
I can't scrub this out on the way to the server from the client, as it is entirely 'server code,' and valid javascript.

I could scrub the code in the barrier between JS and ruby, but- that would probably have to happen in the translation layer between JS -> Ruby. Or maybe right after.
I'll see if I can put together a test case for this in mini_racer.

I'm also curious why it says ascii-8bit now. I'll look into it. Hard to know where those messages are coming from, b/c this is just stderr / stdout piped to a logfile.

**Comment by seanmakesgames** [comment]
I've figured out to a very strong degree of confidence the segfaults and other memory related errors. They are 100% related to garbage collection happening in attached procs during execution.
I think you are good to update versions here. As long as it's shown as a 'known issue' w/ a workaround.
#41

**Comment by SamSaffron** [comment]
ok I am ready for a release ... try out prerelease this week if no complaints will be releasing stable next

```
gem install mini_racer --pre
```

**Comment by darix** [comment]
thank you \o/

**Comment by SamSaffron** [comment]
new version is out !! @wk8  @darix @seanmakesgames  @ignisf  

🎊
