### ISSUE TITLE
Call passed JavaScript anonymous function from Ruby

### ISSUE THREAD

**Issue by eltiare** [discourse/mini_racer#28]
Example: 

```
context = MiniRacer::Context.new
context.attach('each', ->(f) { [1,2,3].each { |i| f.call(i); } })
context.eval 'i = 0; each(function(i2) { i += i2 }); i' // => 6
```

Is such a thing being considered?

**Comment by SamSaffron** [comment]
This introduces some serious GC concerns, when can ruby clean up these fn refs? 

I am generally against this change cause it blurs the boundaries too much.

**Comment by eltiare** [comment]
Fair enough. It's pretty easy to write workarounds for it anyway. Thanks for the response.
