### ISSUE TITLE
Timeouts during marshalling are sending FailedV8Conversion objects instead of raising

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#29]
Timeouts are happening during marshalling, and are just sending FailedV8Conversion objects into rubyland (where I'm currently just assuming that they are timeouts)

test with consistent repro:
```
  def test_timeout_during_marshall
    context = MiniRacer::Context.new({timeout: 1000})
    context.attach("long_running_proc", proc do |a|
      a[rand(10000).to_s] = "a"
      a
    end)
    assert_raises(MiniRacer::ScriptTerminatedError) do
      context.eval("var a = {}; while(true) { a = long_running_proc(a); }")
    end
  end
```

**Comment by SamSaffron** [comment]
simpler test case is:

```
def test_timeout_in_ruby_land
    context = MiniRacer::Context.new(timeout: 50)
    context.attach('sleep', proc{ sleep 0.1 })
    assert_raises(MiniRacer::ScriptTerminatedError) do
      context.eval('sleep()')
    end
  end
```

We are attempting to terminate execution on an isolate that is not running cause its in an external. this is not going to be easy to fix.

**Comment by seanmakesgames** [comment]
Ok. I hear you. I would love to fix this.
I don't know enough about the threading model and the synchronization to get this right, but I can definitely start taking stabs at it. Maybe you can correct assumptions if I go over it?

main ruby process is loaded
context is created
v8 eval runs on a ruby thread without gvl started up by the c extension
procs are run on ruby threads with gvl
timeout is a thread spawned with pthread

Objects are copied and marshalled across the ruby <-> v8 boundary and are released on either side after they are passed through? (mostly a guess)
procs are the only long-lived object in the framework?

**Comment by seanmakesgames** [comment]
Got a repro for one of my crashes out of this issue. Not the simplest test case, but does the job.

```
def test_undef_mem
  context = MiniRacer::Context.new(timeout: 5)
  context.attach("marsh", proc do |a, b, c|
    puts a
    puts b
    puts c

    return [a,b,c] if a.is_a?(MiniRacer::FailedV8Conversion) || b.is_a?(MiniRacer::FailedV8Conversion) || c.is_a?(MiniRacer::FailedV8Conversion)
    
    a[rand(10000).to_s] = "a"
    b[rand(10000).to_s] = "b"
    c[rand(10000).to_s] = "c"
    [a,b,c]
  end)
  context.eval("var a = [{},{},{}]; while(true) { a = marsh(a[0],a[1],a[2]); }")
end
```

Sample output
```
{}
{}
{}
{1427=>"a"}
{3053=>"b"}
{5572=>"c"}
{1427=>"a", 2774=>"a"}
{2429=>"b", 3053=>"b"}
{3323=>"c", 5572=>"c"}
{1427=>"a", 2774=>"a", 4054=>"a"}
{2429=>"b", 3053=>"b", 9695=>"b"}
{3323=>"c", 5113=>"c", 5572=>"c"}
{1427=>"a", 2774=>"a", 4054=>"a", 4262=>"a"}
{2429=>"b", 3053=>"b", 7952=>"b", 9695=>"b"}
{1414=>"c", 3323=>"c", 5113=>"c", 5572=>"c"}
Exception thrown during bootstrapping
Extension or internal compilation error.
#<MiniRacer::FailedV8Conversion:0x007fc764827138>
{2429=>"b", 3053=>"b", 7074=>"b", 7952=>"b", 9695=>"b"}
{1414=>"c", 3323=>"c", 5113=>"c", 5572=>"c", 6950=>"c"}

#
# Fatal error in v8::Isolate::Dispose()
# Disposing the isolate that is entered by a thread.
#

test/test_undef.rb: [BUG] Illegal instruction at 0x00000109127b92
```

Unfortunately my undefined memory thoughts were not correct, because if we terminate execution during proc args marshalling then we instead pass this object and continue execution. All args are continued to be marshalled, proc is run, then on return, crash. (Pretty sure that's the order)

**Comment by SamSaffron** [comment]
fantastic, will try it out Monday.

**Comment by SamSaffron** [comment]
The resolves the issue and kills the segfault, but getting a correct exception raise is REALLY hard, so we raise, but in some cases do not give out the correct exception

https://github.com/discourse/mini_racer/commit/bcb3027e8f79218aa64a8d541ffd9d4809bbbff4

Can you test?

**Comment by seanmakesgames** [comment]
Yes. I can check it out tomorrow morning (it's late PDT) :)
Thanks for making a fix!!

**Comment by seanmakesgames** [comment]
Ran my test case, seems to be passing correctly. Will investigate the code more thoroughly a bit later today.
Thanks, Sam!

**Comment by SamSaffron** [comment]
OK, maybe try out latest in prd to see if it is crashing any less.

Chrome 53 is just out so MiniRacer is now 2 versions behind, I very much
dislike this. I want to get a new build out.

**Comment by seanmakesgames** [comment]
I've updated prod to latest. I'll let you know how it goes @SamSaffron

**Comment by seanmakesgames** [comment]
The Illegal instruction issue hasn't happened since. :D
Other segfaults have:
https://github.com/discourse/mini_racer/issues/39

**Comment by seanmakesgames** [comment]
I'm satisfied with the stability of this issue.
