### ISSUE TITLE
Ruby 1.9 incompatibiliby (missing thread.h)

### ISSUE THREAD

**Issue by ignisf** [discourse/mini_racer#3]
Hello,

When trying to install on Ruby 1.9 the build fails with a cryptic error about a missing `thread.h`. AFAIK this is related to lack of support of calling threads without a GVL.

IMO an explicit Ruby version requirement should be added to the gemspec in order to save some debugging time of people trying to use the gem with 1.9. See http://guides.rubygems.org/specification-reference/#required_ruby_version=

It seems that Ruby 1.9 is the default in Ubuntu **14.04** which will be supported until **2020**, and **1.8** is the default in **12.04** which will be supported until **2018** :open_mouth:.

**Comment by ignisf** [comment]
Fixed by 4d1ff7cc4c7cea98f5ba1ef1493c32e63405d348

**Comment by SamSaffron** [comment]
sorry, thanks was meaning to mention that !
