### ISSUE TITLE
context hangs with threadlock

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#30]
Have not yet been able to recreate it in mini_racer test suite, but have one test case repro-ing it consistently in my own test suite.

Threadstate at deadlock has a bunch of threads waiting on the TaskQueue:
https://gist.github.com/seanmakesgames/e93830060acfb0e07ce232d072d81fc4

rolling back code to one commit behind head resolves the issue.

more to come.

**Comment by seanmakesgames** [comment]
after a long and complicated isolation process (and quite grumpy at myself now that I have the repro); here it is @SamSaffron :

```
    context = MiniRacer::Context.new
    context.attach("print", proc{|msg| puts msg})
   	
    context.eval "print('foo')"
```

**Comment by SamSaffron** [comment]
Nice, perfect repro ... having a look

**Comment by SamSaffron** [comment]
Ok I think I have this fixed, try out latest!

**Comment by seanmakesgames** [comment]
Nice. It's working w/ libv8 at latest as well
