### ISSUE TITLE
Tests fail with `rb_thread_call_with_gvl: called by a thread which has GVL` on OSX

### ISSUE THREAD

**Issue by ignisf** [discourse/mini_racer#32]
It seems that V8 5.2.361.43 causes a bug in mini_racer.

Full log: https://travis-ci.org/discourse/mini_racer/jobs/147846400

**Comment by seanmakesgames** [comment]
Haha, this is totally what was being fixed by the latest commit: https://github.com/discourse/mini_racer/commit/ff543d24e8a69f4a4012f848cbd857d8188dafcd

**Comment by ignisf** [comment]
Did you try with the updated version of libv8?

**Comment by seanmakesgames** [comment]
Nope. Hadn't :)
I can confirm failure after update of libv8.
There are other issues with the fix as well, but I don't know enough about the threading model to propose a fix for them yet.

**Comment by SamSaffron** [comment]
yeah this is fixed, good catch ... shame I can't use https://github.com/discourse/mini_racer/commit/6bfefdb10f815fc626933dc39c91b880e06ca0b3

ruby_thread_has_gvl_p only works on ruby 2.3 it appears :(
