### ISSUE TITLE
Need a way to prevent timeouts from halting execution in specific regions

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#34]
This is a pretty specific use-case, but I need a way to make certain sets of operations 'atomic' -- that is to say, I need them to not be terminated by execution timer until after they are completed.
I would probably use attached procs to control on/off. Currently, I'd need to rescue the termination exception and undo/replay things, which is a mess.
Any ideas on how to implement this in mini_racer (or outside)?

**Comment by SamSaffron** [comment]
I think cleanest solution is to allow eval to accept a timeout value that can override the context timeout. at least that is intuitive. allowing externals to fiddle with this is going to be very messy to consume.

**Comment by seanmakesgames** [comment]
In the context of my framework, consumers get their one eval which runs their JS code until it times out. Proc code is owned by me and does things like access the database. I need to be able to ensure that the procs don't time out.

Like I said initially this is 'a pretty specific use-case' so I didn't expect it to look good in mini_racer. I'm happy to implement this just for myself on my fork, but I don't have enough area knowledge to get it done.

**Comment by SamSaffron** [comment]
I am very very against forks, they just end up hurting everyone long
term...

Start by outlining an API, then we can think this through.

**Comment by seanmakesgames** [comment]
Will do and sounds good. Ill work on that in the morning.
Thanks for your support.

**Comment by seanmakesgames** [comment]
Was just writing up a test case for how this would work, and I must be going crazy, because procs are already atomic
  
```
  def test_atomic_procs
    v8 = MiniRacer::Context.new(timeout: 50)
    count = 0
    v8.attach('count', proc{|x| count -= 1; spin = 0; 3000.times { spin += 1 if (spin != 0) }; count += 1 }) # can't use sleep(0.1) here for some reason, also this is a bit overkill in the spin department.

    assert_raises(MiniRacer::ScriptTerminatedError) do
      v8.eval "while(true) { count(); }"
    end

    assert_equal(count, 0)
  end
```

maybe check my work?

Maybe 
`V8::TerminateExecution(data->context_info->isolate_info->isolate);`
doesn't take effect until js execution is resumed (from proc execution)

thoughts?
