### ISSUE TITLE
fatal error: include/v8.h: No such file or directory when old versions of libv8 present

### ISSUE THREAD

**Issue by ignisf** [discourse/mini_racer#38]
See #37. A workaround is to run `bundle clean` or `gem uninstall libv8`.

**Comment by ignisf** [comment]
I think `therubyracer` handles this with https://github.com/cowboyd/therubyracer/blob/master/ext/v8/extconf.rb#L21-L30

**Comment by SamSaffron** [comment]
hmmm how is this going to be possible if we now have proper deps on 5.3 in gemspec?

**Comment by ignisf** [comment]
OK, let's close this for now and see how things go.
