### ISSUE TITLE
[BUG] object allocation during garbage collection phase

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#41]
Managed to get this one in my game's test suite.
https://gist.github.com/seanmakesgames/89fb4dac1761666770176f9b03bb54f3

I'll try to put together a test case in mini_racer that repros it.

**Comment by seanmakesgames** [comment]
Looks like my workers are working too long without a garbage collection. If GC triggers inside a proc which has GVL, I'm sure some other c-code somewhere is doing the allocation that's causing the error. I'm pretty sure I can fix the issue on my side, by making sure to explicitly call GC.start before doing an eval.
I'm sure there are some cases where attached procs might alloc enough memory on their own during an eval to cause a GC.

Here's the test case:

```
  def test_start_gc
    context = MiniRacer::Context.new(timeout: 10)
    context.attach("echo", proc{|msg| GC.start; msg})
    GC.disable
    100.times { 'foo' } # alloc a handful of objects
    GC.enable
    assert_equal("foo", context.eval("while(true) echo('foo');"))
  end
```

**Comment by seanmakesgames** [comment]
adding the GC.start before I run run any eval has mostly prevented the crashes, but adds 100ms to all of my execution times.

In fact, now that I'm thinking about it, I haven't gotten a c-level crash in a few days... of any kind.

**Comment by seanmakesgames** [comment]
I moved garbage collection (GC.start) to after the eval and the crashes have come back, but in less numbers. Feel like this is a really strong indicator for all of the issues. I'm going to disable garbage collection around the eval call and see if crashes go away again.

**Comment by seanmakesgames** [comment]
I have confirmed that under stress testing there is ZERO instances of c-level crashes (or strange ruby crashes) when garbage collection is turned off during js eval. I'm closing and referencing this issue as a 'cause'

**Comment by SamSaffron** [comment]
Let me know how this goes: 

https://github.com/discourse/mini_racer/commit/6fbec25677d1fb14f8a5b6c4ba10fbccf4285307

Pretty sure I fixed this issue.

**Comment by seanmakesgames** [comment]
Today is launch day. I won't be able to test for a while probably. Have you run the 'tight-loop' test? (I don't have time rn)

```
  def test_segfault
    5000.times do
      GC.start

      context = MiniRacer::Context.new(timeout: 5)
      context.attach("echo", proc{|msg| msg.to_sym.to_s})
      assert_raises(MiniRacer::EvalError) do
        context.eval("while(true) echo('foo');")
      end
    end
  end
```

**Comment by SamSaffron** [comment]
OK, closing this, I think this is fixed in the pre-release
