### ISSUE TITLE
passing invalid utf8 out to attached ruby proc causes extension-level crash

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#42]
```
#
# Fatal error in v8::Isolate::Dispose()
# Disposing the isolate that is entered by a thread.
#

/Users/seangubelman/mini_racer/test/mini_racer_test.rb:448: [BUG] Illegal instruction at 0x0000010a1deb42
```

```
  def test_invalid_utf8_proc
    context = MiniRacer::Context.new
    context.attach('echo', proc{|v| return v })
    assert_raises(MiniRacer::ParseError) do
      context.eval('echo("\uDC00");')
    end
  end
```

JS is natively utf16, so the code being eval'd is valid. I figure we raise something like 'Invalid UTF8 string passed to attached proc'

P.S. My players are excellent at making my life difficult. ;P

**Comment by SamSaffron** [comment]
I am all for adding proper UTF-16 support but this particular issue is nothing to do with conversion

```
 context.attach('echo', proc{|v| return v })
```

Should be 

```
context.attach('echo', proc{|v| v })
```

return from a proc has very very confusing semantics ... 

```
irb(main):007:0> @my_proc = proc{return "hi"}
=> #<Proc:0x007f211dbad7c8@(irb):7>
irb(main):008:0> def x; puts 1; @my_proc.call; puts 2; end
=> :x
irb(main):009:0> x
1
LocalJumpError: unexpected return
```

vs

```
irb(main):010:0> @my_lambda = lambda{return "hi"}
=> #<Proc:0x007f211db7ded8@(irb):10 (lambda)>
irb(main):011:0> def x; puts 1; @my_lambda.call; puts 2; end
=> :x
irb(main):012:0> x
1
2
=> nil
```

Use lambdas, not procs

**Comment by seanmakesgames** [comment]
Indeed, I'm not able to repro the issue with this simplified test, which means it's probably in my ruby code on the other side of the attached method somewhere.

Looks like after adjusting the test case, the 'malformed utf8' can travel safely to and from rubyland as I assume you discovered after fixing my typo.

I also have added some code to strip out invalid utf8 chars coming in from JS as a post-process operation.

There's probably a better way (use utf-16 encoded strings being passed into attached methods? maybe?)

Anyhow. Thanks for the assist.

**Comment by SamSaffron** [comment]
I am totally open to adding utf16 support but it gets pretty hairy and we would need to be super careful not to make all string handling slower just cause we add support for it.

**Comment by seanmakesgames** [comment]
Yeah, it's a tough proposition, because in terms of stability, having all the strings that are passed into attached methods matching JS string formats should reduce friction at this barrier- but utf16 is definitely a heftier encoding--
does seem like it would be more performant to not change the encoding of the strings when traveling between rb&js though.
