### ISSUE TITLE
timeout can be bypassed by returning an object with a property.

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#43]
This one's real bad. Can't even write a test case that properly fails & doesn't hang:

```
  def test_timeout_break
    context = MiniRacer::Context.new(timeout: 10)

    status = Timeout::timeout(0.05) do # this doesn't even work
      context.eval('var a = {ok:true, get msg(){ while(true); }}; a')
    end
  end
```

In the interim, I'll be wrapping return values in a stringify/parse block to remove getters from post-return execution.

**Comment by seanmakesgames** [comment]
This can also be accomplished with a throw.

```
var e=new Error();
e.__defineGetter__('message',function(){while(1) ;});
throw e;
```

**Comment by SamSaffron** [comment]
This is complicated to fix and the only fix I can think of comes with some serious tradeoffs. 

What is happening is that the thread that converts the V8 object to a Ruby object owns the GIL, this must be the case cause it is allocated ruby objects. 

The timeout thread is a ruby thread and it gets 0 time to run IF the GIL is blocked... so what happens is that it just hangs. 

The main trick around this is to convert all return values of evals to JSON first and then convert back to a JS object from there... trouble is that this is not super efficient and I would prefer if this was not in core. 

So for now ... simply wrap all the JS stuff you are running with 

```
JSON.parse(JSON.stringify(return(function(){...stuff..))()))
```
That will protect you from this class of errors ... I am tempted to just close this and document this in the readme... 

OR if we can cleanly add a helper in context I am open to add "timeouts_in_conversion: true" option

**Comment by seanmakesgames** [comment]
Yep. Wrapping it with a stringify/parse pair is my current solution (brings the execution of that code into the scope of the eval() call)

I'm fine with 'won't fix' on this one. Just wanted to make sure it was documented / brought to attention. :)

**Comment by SamSaffron** [comment]
Feel free to add some doco to the readme to clarify, its just way to messy
to fix

**Comment by seanmakesgames** [comment]
will do. have added it to my list. :)
