### ISSUE TITLE
able to catch ruby proc exceptions with try/catch in JS, but they have no information

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#44]
Would love to prevent the 'catch' and forward them out to ruby if possible.

```
  def test_catch_rb
    context = MiniRacer::Context.new(timeout: 50)
    context.attach('crash', proc{ raise ArgumentError.new('???') })

    code = "function a() { \
              try { \
                crash(); \
              } catch(e) { return e; } \
            }\
            a();"

    assert_raises(ArgumentError) do
      context.eval(code)
    end
  end
```

**Comment by SamSaffron** [comment]
this would be pretty messy to add, not against it, but not an easy change

**Comment by seanmakesgames** [comment]
understood. Can you describe the issue a bit and maybe I can take a stab at it (or have one of my players take a look?)

**Comment by seanmakesgames** [comment]
To solve this error (and others like it) I'm removing player ability to try/catch in their code.
This is still an issue, but it will be low pri for me. Feel free to close if you desire. :)

**Comment by SamSaffron** [comment]
Yeah I think it makes sense to close, it feels a bit obscure and complex to add to mini racer
