### ISSUE TITLE
mini_racer libv8 dependency problem

### ISSUE THREAD

**Issue by kikonen** [discourse/mini_racer#46]
When trying "bundle update" today I just got following error:

```
Could not find libv8-5.0.71.48.5 in any of the sources
```

**Comment by lucaspiller** [comment]
I just came across this exact problem, the latest version from GitHub works for me:

```
gem 'mini_racer', github: 'discourse/mini_racer'
```

**Comment by ignisf** [comment]
I just yanked `5.0.71.48.5-arm-linux` from rubygems. Please try again while I kick myself how careless I am.

**Comment by SamSaffron** [comment]
cool, 0.1.5 pre is now out, it explicitly depends on 5.3  and up
