### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by koops** [discourse/mini_racer#5]
Hi, this project looks exciting. I'm a long-time therubyracer user and I use it for long-running contexts. Memory management is an open issue with trr, see [issue](https://github.com/cowboyd/therubyracer/issues/350).

So I'd like to know, is there any reason to believe that mini_racer might do better than trr at conserving memory?

**Comment by SamSaffron** [comment]
Yes mini_racer is designed to hold almost no refs between VMs. The only refs allowed are an array of procs it is allowed to call. 

By avoiding transparently holding references and weak refs to objects between VMS (everything is moved by copy) risk of memory issues goes way down.

**Comment by koops** [comment]
Thanks, that's good news. One other, related thing: do you plan on supposing dispose on a context?

**Comment by SamSaffron** [comment]
Yes going to add a mechanism to run a context in a block and dispose of all
v8 resources once block is over "burning" the context,

Also maybe simply add a reset method to clear
