### ISSUE TITLE
mini_racer_extension.so: undefined symbol: _ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm

### ISSUE THREAD

**Issue by niko** [discourse/mini_racer#50]
When running `MiniRacer::Context.new` I get the following error:
```
ruby: symbol lookup error: /usr/local/lib/ruby/gems/2.3.0/gems/mini_racer-0.1.6/lib/mini_racer_extension.so: undefined symbol: _ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm
```
I'm using ruby 2.3.1 and bundler within a Docker container running debian:wheezy on an Ubuntu 16.04 Docker host and an Arch Linux Docker host. Natively on Arch it works.
```
uname -a
Linux lfm-docker-8 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```
It happens with mini_racer 0.1.6 and 0.1.7.

**Comment by niko** [comment]
Maybe I just found the answer. I have gcc version 4.7.2 (Debian 4.7.2-5). Trying to upgrade to 4.8.

**Comment by niko** [comment]
Yup. That's it. Updated to Debian 8.3 with gcc 4.9. Now it works. Closing.

**Comment by fgi** [comment]
I have same issue but I am on Debian 7 so I can't upgrade gcc to 4.8.
Do you know if there  is an alternative?
Thanks.

**Comment by ignisf** [comment]
Not sure what's the situation with clang on Debian, but theoretically one could `export CXX=clang` and try to install the gem this way.

**Comment by fgi** [comment]
I tried that. But it did not work.
mini_racer requires gcc 4.7+ (4.8+ it seems) or clang 3.2+. On Debian 7, clang package is 3.0.
