### ISSUE TITLE
Disposing contexts

### ISSUE THREAD

**Issue by koops** [discourse/mini_racer#52]
Maybe I'm missing it, but there doesn't seem to be a way to release a context and free memory.

This would be very handy given that timeouts can leave the context in an inconsistent state (`finally` blocks aren't called, etc.)

Thanks again for your work on miniracer.

**Comment by SamSaffron** [comment]
Agree, I would like a mechanism to rush clearing context, perhaps a block
form.

Would you like to work on this?

**Comment by koops** [comment]
I would like to work on this, yes. But don't wait for me :)

**Comment by SamSaffron** [comment]
I just added support for `context.dispose` in 0.1.10 !

**Comment by koops** [comment]
Beautiful, thank you!
