### ISSUE TITLE
upgrade v8 version

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#53]
There's a tasty new version of v8 available. We should get it. ;)

**Comment by ignisf** [comment]
Already in the libv8 repo, was thinking about a pre-release

**Comment by seanmakesgames** [comment]
excellent @ignisf !

**Comment by ignisf** [comment]
oh yeah.. wait... the libv8 master is already at 5.6 :P

**Comment by seanmakesgames** [comment]
@SamSaffron just a dependency upgrade then?

**Comment by SamSaffron** [comment]
Yes please, do a PR to upgrade us to 56 ... as a rule of thumb I am
perfectly happy upgrading the dependency to latest stable when v8 stable is
released.

**Comment by SamSaffron** [comment]
@ignisf can you do a new release of libv8 ? would love to upgrade our dependency to 5.6, chrome stable is on 56 these days (58 btw is going to be very exciting cause there are some very exciting optimisations enabled by default)

**Comment by ignisf** [comment]
Was just about to do that... I'm going to need a server farm soon to produce all the binaries, seeing how much time it takes me :D. Will try to cut a pre-release first, @seanmakesgames which OSes are you using to develop and test so I can prioritise them?

**Comment by seanmakesgames** [comment]
@ignisf server ubuntu 14.04 64; dev macos 10.11.6

**Comment by ignisf** [comment]
linux binary up, macos binaries as soon as Travis is finished compiling them

**Comment by ignisf** [comment]
https://rubygems.org/gems/libv8/versions/5.6.326.50.0beta1 🎉

**Comment by seanmakesgames** [comment]
awesome :D
Sorry for the slowness, updating my branch and checking out my game's test suite.

**Comment by seanmakesgames** [comment]
updated gemspec locally, mini_racer tests all run great. Doing the game ones now (takes a bit)

**Comment by seanmakesgames** [comment]
Everything looks good with the 5.6.326.50.0beta1 version in my mac dev environment. :)
Once '~> 5.6' is a thing that works in the gemspec, I can make PR.

**Comment by ignisf** [comment]
I have those https://github.com/cowboyd/libv8/milestone/4 to fix before I release a stable version. Maybe you could focus on the OOM stuff in the meantime? I'll try to do it later today (it's 2AM here).

**Comment by seanmakesgames** [comment]
haha yeah, it's no problem at all.
Thanks for the support! Keep us posted. :D

**Comment by seanmakesgames** [comment]
ping @ignisf

**Comment by ignisf** [comment]
I'm finally ready for a release. 5.7.492.65.0 is imminent

**Comment by seanmakesgames** [comment]
Oh! 5.7 eh? Nice :D

**Comment by ignisf** [comment]
beta up for testing. Take it for a spin with your test suites please and ping me.

**Comment by seanmakesgames** [comment]
Will do! Thanks @ignisf

**Comment by seanmakesgames** [comment]
@ignisf ugh I totally haven't forgotten about this-- it's been sitting on my todolist this whole time. Few fires at work totally deprioritized this. Definitely haven't forgotten about it though.

**Comment by krzysiek1507** [comment]
Hi @seanmakesgames any news? ;)

**Comment by seanmakesgames** [comment]
Thanks for the ping @krzysiek1507 -- Running the test suite now! :D

**Comment by seanmakesgames** [comment]
@ignisf @krzysiek1507 Tests are all passing here. Ready for a release so I can 'test it out' on production. ;)

**Comment by ignisf** [comment]
acknowledged. Will ping you when ready.

**Comment by seanmakesgames** [comment]
Sorry it took forever.

**Comment by krzysiek1507** [comment]
@seanmakesgames I hope your production still works. 😄

**Comment by seanmakesgames** [comment]
haha-- we'll find out soon enough. This game is broken by design, so 'works' is up to interpretation. ;)

**Comment by SamSaffron** [comment]
just wanted to note here, that my goal for MiniRacer has always been **always** to be on latest stable v8.

**Comment by seanmakesgames** [comment]
Once this one gets out, we can start work on the next version?

**Comment by ignisf** [comment]
released. Working on 5.9 in the respective branch.

**Comment by SamSaffron** [comment]
@ignisf I just bumped mini racer, but when I updated discourse I see this in my lockfile

```
-    libv8 (5.7.492.65.1)
+    libv8 (5.9.211.38.1-x86_64-linux)
```

Any idea why it is happening? (the linux suffix)

**Comment by SamSaffron** [comment]
MiniRacer is updated 🥇  btw, huge thanks, the benches are a bit of a mixed bag, not a huge win for our workloads and in many places a small loss.

**Comment by ignisf** [comment]
Did you update a Discourse instance running on Linux? If that's the case, then your rubygems preferred the binary version of the gem for Linux, which is the expected behaviour.

**Comment by SamSaffron** [comment]
I did, I ended up just removing the suffix and all seems fine
