### ISSUE TITLE
Mini_racer equivalent for therubyracer .call() method?

### ISSUE THREAD

**Issue by Bramanga** [discourse/mini_racer#59]
I'm trying to use mini_racer in place of therubyracer for [this project](https://github.com/Bramanga/middleman-search), but I'm not sure how to substitute the following logic (see below). There is no `.call()` method for a mini_racer context function. Is there some sort of equivalency for this functionality or workaround for this? 
```ruby
        # Build lunr based on config
        lunr = context.eval('lunr')
        lunr_conf = proc do |this|

          # Use autogenerated id field as reference
          this.ref('id')

          # Add functions to pipeline (just registering them isn't enough)
          @pipeline.each do |name, function|
            this.pipeline.add(context[name])
          end

          # Define fields with boost
          this.use(lunr_lang) if @language != 'en'
          @fields.each do |field, opts|
            next if opts[:index] == false
            this.field(field, {:boost => opts[:boost]})
          end
        end

        # Get lunr index
        index = lunr.call(lunr_conf)
```
[Above code here](https://github.com/Bramanga/middleman-search/blob/master/lib/middleman-search/search-index-resource.rb#L53)

`index = lunr.call(lunr_conf)` results in the error: 
`undefined method 'call' for #<MiniRacer::JavaScriptFunction:0x007fc392b4a778>`

**Comment by SamSaffron** [comment]
Can't you just use `eval` here.

```
ctx.eval('x = function(y){ return y+1; }')
puts ctx.eval('x(2)')
# 3
```
