### ISSUE TITLE
Better Error Backtraces

### ISSUE THREAD

**Issue by tisba** [discourse/mini_racer#61]
(only slightly related to https://github.com/discourse/mini_racer/issues/58).

I was wondering, if there is a way to load JavaScript files, instead of evaluating them by passing a string. Or to give some source/context name to V8.

At the current case I'm working on, there is some base code, that is always loaded. Then some semi-user input is evaluated on top of that code. I'm having a hard time to filter and massage error back traces so that they are meaningful to my users.

Is there a way to provide some names for sources or contexts, so that `unknown source` and `<anonymous>` are more helpful?

```
ReferenceError: meh is not defined
    at bar (eval at execute (unknown source), <anonymous>:4:3)
    at eval (eval at execute (unknown source), <anonymous>:7:1)
    at Function.execute (<anonymous>:24:5)
    at eval_wrapper (<anonymous>:2:31)
    at <anonymous>:1:1
```

**Comment by SamSaffron** [comment]
Yeah I would love to improve this, I was hitting the exact issue today.

Do you want to give it a shot. I think when evalling we should optionally
allow you to specify a filename.

On Wed, Jul 12, 2017 at 11:44 AM, Sebastian Cohnen <notifications@github.com

**Comment by tisba** [comment]
I'd love to help, but have little to nothing when it comes to experience with C/C++ :-/ If it's not too deep buried in C++/V8 land I'd like to give it a try, if you can point me in the right direction.

**Comment by SamSaffron** [comment]
OK per https://github.com/discourse/mini_racer/commit/2f484fe1b920e9082e2e76f0432f0f6e22ea0636 we now have filename support!

**Comment by tisba** [comment]
That's awesome! Thanks!
