### ISSUE TITLE
trying to swap in mini_racer

### ISSUE THREAD

**Issue by edk** [discourse/mini_racer#62]
Hi!

I've started looking at replacing therubyracer from a large old project with mini_racer.  One of the issues i've run into is that common.js is trying to call the js runtime using a method that is [not available in mini_racer](https://github.com/cowboyd/commonjs.rb/blob/master/lib/commonjs/environment.rb#L29)

Do you have any comments or suggestions w.r.t the general issue of compatibility?  At the moment, it looks like i may need to hack mini_racer to be more api compatible with therubyracer, or should i update the dependencies (commonjs, less.rb, etc) to be mini_racer friendly?  What is your thoughts on accepting potential pr's that attempt to make the api compatible with therubyracer?

Thanks!

**Comment by SamSaffron** [comment]
We don't really intend to add CommonJS comparability, execjs https://github.com/sstephenson/execjs is where its at. 

less rb should be re-written to use execjs. We do not really intend to have a compatible api with therubyracer it is way too wide.

**Comment by edk** [comment]
ok, fair enough, and thanks for the info.  Appreciate it 👍    I'll try to attack it from the less.rb side of things.
