### ISSUE TITLE
GVL lock issue with recursive attached proc calls

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#69]
`rb_thread_call_with_gvl: called by a thread which has GVL`

Here's a test case:
```
  def test_attached_recursion
    context = MiniRacer::Context.new(timeout: 20)
    context.attach("a", proc{|a| a})
    context.attach("b", proc{|a| a})

    context.eval('const obj = {get r(){ b() }}; a(obj);')
  end
```

Ideally this would be some sort of exception instead of a c-level crash. What do you think @SamSaffron?

**Comment by SamSaffron** [comment]
Ouch, do you care to give fixing it a shot?

**Comment by seanmakesgames** [comment]
Definitely.

**Comment by seanmakesgames** [comment]
@SamSaffron: @n00bish graciously agreed to help out with this one, and it seems like the right way to fix it is to just properly flag the transition to gvl-land. He's made a note in his PR.
Take a look when you can. (and at my PRs too!) :D
