### ISSUE TITLE
Issues installing mini_racer: C++11 requires a space between literal and identifier

### ISSUE THREAD

**Issue by tnewell5** [discourse/mini_racer#73]
Hi - I'm having trouble with the mini_racer installation and was hoping you could look into this or point me in the right direction?

![image](https://user-images.githubusercontent.com/8727588/34451205-41402db0-eced-11e7-9d2b-490946548394.png)

![image](https://user-images.githubusercontent.com/8727588/34451209-62309d34-eced-11e7-9cb6-445a69545209.png)

Thanks!
Tanya

**Comment by ignisf** [comment]
Hello @tnewell5,

This looks to me like an issue with Ruby itself that only manifests when building mini_racer.

Could you share a bit more about your platform with us? What version of Ruby are you using? Where did you install it from? rbenv? homebrew? What compiler and version are rubygems trying to use?

**Comment by tnewell5** [comment]
thanks - I'll try another route

**Comment by SamSaffron** [comment]
Hi @tnewell5, any luck here?

**Comment by tnewell5** [comment]
Hi @SamSaffron please feel free to close this issue. I needed mini_racer for react_on_rails but decided not to proceed with react_on_rails at this time.
