### ISSUE TITLE
Questions regarding Sidekiq+MiniRacer

### ISSUE THREAD

**Issue by whistlerbrk** [discourse/mini_racer#77]
Hello, I apologize in advance if this is not a good place to open a support-style question, I read the CoC and the notes at that end of the README and didn't see an alternative.

I've developed a spreadsheet application which uses (the wonderful) MathJS library on the frontend to calculate the results of user defined formulas. However, rather than shipping these results to the backend, I re-calculate them on the fly with a job executed by Sidekiq.

The job was originally using ExecJS w/TheRubyRacer, but I of course ran into a mysterious dead-locking issue and realized it wasn't threadsafe, and then switched to MiniRacer as a result.

However, I am still observing memory usage growing until Heroku terminates this 1Gb RAM instance. I suspect my implementation is causing the issue and it isn't related to https://github.com/mperham/sidekiq/pull/3756 for example. Being that this is on Heroku and not a real VPS, it is hard for me to attach rbtrace and dump the heap and find out myself.

I am considering using MiniRacer directly w/o the ExecJS shim, but I am having trouble understanding a few topics covered in the README.

First, in "GIL free JavaScript execution", the example says:

```
context = MiniRacer::Context.new
Thread.new do
  sleep 1
  context.stop
end
context.eval 'while(true){}'
# => exception is raised
```

Do I need to explicitly stop my context?

Next, snapshots:

```
snapshot = MiniRacer::Snapshot.new('function hello() { return "world!"; }')

context = MiniRacer::Context.new(snapshot: snapshot)
```

Since this is running in Sidekiq, can I stash my snapshot in say memcached/dalli, and then pull it out during the jobs runtime? I assume this would be fine.

Finally, some abbreviated code, it's a little hacked together...

```
class MathJS
  MATHJS_SOURCE = Rails.root.join('vendor', 'mathjs-3.20.1.min.js')

  def self.context
    @context ||= ExecJS.compile(File.read(MATHJS_SOURCE))
  end

  def self.call(function, *args)
    Rails.logger.info("calling mathjs #{function} on #{args}")
    MathJS.context.call(function, *args)
  end
end
```

and then the job, again abbreviated:

```
class SurveyWorker
  include Sidekiq::Worker
  def perform(survey_id)
    @survey = Survey.find(survey_id)
  
    Formula.cache.each do |formula|
      build_and_evaluate(formula)
    end
  end

  def build_and_evaluate(formula)
    # some business logic to build up the formulas variables, it's 'scope'
    scope = ...
    evaluation = MathJS.call('math.eval', formula.formula, scope)
  end
end
```

and finally, for the sake of completion, the Formula class, abbreviated

```
class Formula < ApplicationRecord
  def self.cache
    Rails.cache.fetch('parsed_formula') do
      Formula.all.order(execution_order: :asc).each(&:parse)
    end
  end

  def self.expire_cache!
    Rails.cache.write('parsed_formula', nil)
  end

  def parse
    @parsed_formula ||= MathJS.call("math.parse", formula)
  end
end
```

Sorry the length of this all and a very specific issue for me, though I suspect that using MiniRacer w/Sidekiq is a great use case, so maybe it'll help others.

**Comment by SamSaffron** [comment]
You do not have to stop contexts they are automatically garbage collected, this just allows you to rush reclamation of memory. 

You can not stash snapshots I don't think we have a binary serialization format for them (nor do I think it would be practical)
