### ISSUE TITLE
Could not find libv8-5.0.71.48.3 in any of the sources

### ISSUE THREAD

**Issue by barrywoolgar** [discourse/mini_racer#8]
Hello, I'm having a problem installing this gem with bundler. It fails when resolving dependencies, with the error: `Could not find libv8-5.0.71.48.3 in any of the sources`

I'm not sure if this is an issue with `mini_racer` or with `libv8` versions on rubygems, so can report there if you'd prefer?

Thanks!

**Comment by ignisf** [comment]
Hello, could you provide the output of `ruby -e 'puts Gem::Platform.local'`

**Comment by ignisf** [comment]
I had forgotten to push the source distribution of the 5.0.71.48.3 version of libv8. It's up now, but expect huge compile time at best and compilation failure at worst, since your platform seems to not be officially supported by the libv8 gem.

**Comment by barrywoolgar** [comment]
Thanks @ignisf, the output is `x86_64-darwin-13` - Which is my OSX 10.9.5 dev box - I'm sure our production environment has a more common architecture!

**Comment by ignisf** [comment]
Yeah, we have no convenient way of producing libv8 binaries for OS X 10.9. Anyway, that's not an issue with mini_racer.

**Comment by barrywoolgar** [comment]
Thanks for explaining that, no worries. Will close this now!
