### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by AntonBerez** [discourse/mini_racer#83]
Can you help me with this issue? I need that for react on rails.
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Rails 4.2.6
gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5

Issue:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20180402-4622-17ue5rwmini_racer-0.1.15/gems/mini_racer-0.1.15/ext/mini_racer_extension
/usr/bin/ruby2.3 -r ./siteconf20180402-4622-1pv3sy3.rb extconf.rb
checking for main() in -lpthread... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-pthreadlib
	--without-pthreadlib
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)

You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'

	from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'

	from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'

	from /usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'

	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'

	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'

	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'

	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'

	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'

	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'

	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'

	from /usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'

	from extconf.rb:4:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /tmp/bundler20180402-4622-17ue5rwmini_racer-0.1.15/extensions/x86_64-linux/2.3.0/mini_racer-0.1.15/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20180402-4622-17ue5rwmini_racer-0.1.15/gems/mini_racer-0.1.15 for inspection.
Results logged to /tmp/bundler20180402-4622-17ue5rwmini_racer-0.1.15/extensions/x86_64-linux/2.3.0/mini_racer-0.1.15/gem_make.out

**Comment by ignisf** [comment]
Hi,

```
 /usr/lib/ruby/2.3.0/mkmf.rb:456:in try_do': The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first. from /usr/lib/ruby/2.3.0/mkmf.rb:541:intry_link0'
```

Do you have the `build-essential` and `ruby-dev` packages installed? You can install them by issuing `apt-get install ruby-dev build-essential`.

**Comment by AntonBerez** [comment]
Thank you very much for fast answer. I didn't have 'build-essential'. Now works.

**Comment by ignisf** [comment]
Pleasure
