### ISSUE TITLE
Context#eval not synchronous

### ISSUE THREAD

**Issue by grrowl** [discourse/mini_racer#84]
We're loading a big JS runtime into a mini_racer context via `Context.eval(File.load('renderer.js'))` (which defines `Renderer` in the current scope), then immediately after we `.eval('Renderer.default({ some: 'big object' })`. We cache the Context in a singleton to avoid parsing the `renderer.js` more often that necessary.

During tests, the first method to our Context singleton occasionally fails on the second `.eval` call with a MiniRacer/V8 error: `Renderer is not defined`. Subsequent calls (which re-use the Context, skipping the `.eval(File.load())` dance) succeed. It seems like the `Renderer` is not available immediately after its `#eval` call returns.

Is this expected behaviour? Currently our workaround is to call `(typeof Renderer !== 'undefined')` until it's true, then proceed with calls against our Renderer.

**Comment by SamSaffron** [comment]
Can you reproduce this in a script?

**Comment by grrowl** [comment]
Can't manage reproduce this in a smaller testcase for now, but will keep an eye out for it in future. Cheers 👍
