### ISSUE TITLE
Handling of "V8 isolate was forked"?

### ISSUE THREAD

**Issue by tisba** [discourse/mini_racer#99]
We see `WARNING: V8 isolate was forked, it can not be disposed and memory will not be reclaimed till the Ruby process exits.` when running specs and other tasks.

I'm trying to figure out how to handle those warnings properly. E.g. we use MiniRacer together with FactoryBot. My assumption currently is that I have to shut down `MiniRacer::Context` instances properly after usage. But I'm not sure how to do that. Calling `#stop` seems not to be sufficient.

**Comment by SamSaffron** [comment]
The reason you are seeing this is cause V8 does not support forking at all. If a master process has any contexts in it that are live they can not be properly freed in the forked process. 

At discourse we simply never create any contexts in parent processes and only create in child processes. 

`context.dispose` though should allow you to clean up the mess in the parent prior to forking.

**Comment by tisba** [comment]
Thanks for the info! I'm still trying to figure out why this happens, because there should be no alive reference to a `MiniRacer::Context` instances.

I'll give `#dispose` a try and so far this seems to work fine. Since we don't have any long living instances of contexts it should be rather simple to wrap this in a way to always call `#dispose` when done automatically.

**Comment by tisba** [comment]
Thinking about what I just said it makes sense. When no GC has happened it doesn't really matter if there is no alive reference when the process gets forked.
